export const LINK1 = 'http://www.omdbapi.com/?s=Matrix&apikey=720c3666'
export const LINK2 = 'http://www.omdbapi.com/?s=Matrix%20Reloaded&apikey=720c3666'
export const LINK3 = 'http://www.omdbapi.com/?s=Matrix%20Revolutions&apikey=720c3666'
export const PENDING = 'pending'
export const FULFILLED = 'fulfilled'
export const REJECTED = 'rejected'